# fab/pillows/production.yml
---
exclude_pillows:
  - kafka-ucr-main
include_pillows:
  - custom.opm.models.OpmUserFluffPillow
  - custom.reports.mc.models.MalariaConsortiumFluffPillow
  - custom.m4change.models.M4ChangeFormFluffPillow
  - custom.intrahealth.models.IntraHealthFormFluffPillow
  - custom.intrahealth.models.RecouvrementFluffPillow
  - custom.care_pathways.models.GeographyFluffPillow
  - custom.care_pathways.models.FarmerRecordFluffPillow
  - custom.world_vision.models.WorldVisionMotherFluffPillow
  - custom.world_vision.models.WorldVisionChildFluffPillow
  - custom.world_vision.models.WorldVisionHierarchyFluffPillow
  - custom.up_nrhm.models.UpNRHMLocationHierarchyFluffPillow
  - custom.up_nrhm.models.ASHAFacilitatorsFluffPillow
  - custom.succeed.models.UCLAPatientFluffPillow
  - kafka-ucr-main-08
  - kafka-ucr-main-9f
